---
title       : "Support de restructuration"
subtitle    : "Réponse à vos questions"
author      : Sylvain Tenier
job         : s.tenier@groupe-esigelec.fr
framework   : io2012 # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : mathjax            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

--- 

## Séance précédente : Eclipse, structures conditionnelles

* pas de question

---  #id 

## Structure itérative *for*

* à quoi correspond le i++ ?

```{java boucle_for}
for (int i=0;i<=10;i++)
{
  System.out.println("Voici la ligne "+i);
}

```

---

## Structure itérative *while* / *do .. while* (1)

 - Combien d'itérations ?

```{java boucle_while}
int a=15;
while (a<10){
  System.out.println("Rattrapage !")
}
```

---

## Structure itérative *while* / *do .. while* (2)

 - Combien d'itérations ?

```{java boucle_do_while}
int a=15;
do{
  System.out.println("Rattrapage !")
}while (a<10);
```

---

## Application aux tableaux (1)

- Simple boucle

```{java simple_boucle}
String impairs[]={"un","trois","cinq","sept","neuf"};
int nbImpairs=5;
for(int i=0;i<nbImpairs;i++){
  System.out.println(impairs[i]);
}
```

---

## Application aux tableaux (2)

- Double boucle

```{java double_boucle}
String chiffres[][]={ {"un","trois","cinq","sept","neuf"},
                    {"deux","quatre","six","huit","zero"} };
int nbParSerie=5;
for(int i=0;i<2;i++){
  System.out.println("Série :" + (i+1));
  for(int j=0;j<nbParSerie;j++){
    System.out.println(chiffres[i][j]);
  }
}
```

--- .title-slide

## Restructuration séance 4 (Tableaux)

- Structures conditionnelles / itératives alternatives
- Retour sur les tableaux
- Les méthodes statiques

---

## Structures alternatives

- Conditions ternaires
  - Méthode complexe !
  - \(\mathtt{(x < y) ? y : x)}\)
  
- Itérations 
```{java iteration}
String tab[] = {"toto", "titi", "tutu", "tete", "tata"};
for(String str : tab)
  // à chaque itération, str prend la valeur suivante de tab 
  System.out.println(str);
```

---

## Random

- Génération d'un nombre dans l'intervalle \(\mathbf{[min;max]} \)

```{java random}
	public static void main(String[] args) {
		int min=3; // valeur minimale de l'intervale
		int max=45; // valeur maximale de l'intervale
		while(true){
			//tirage aléatoire
			int n=(int)(Math.random()*(max-min+1))+min;
			//affichage pour validation
			if(n==min||n==max||n==(min-1)||n==(max+1))
				System.out.println(n);
		}
```

---

## Classification 

- Utilisation du modulo pour créer un nombre défini de classes à partir de n'importe quel entier positif

```{java classification}
	public static void main(String[] args) {
		int max=1545858; // valeur très grande
		int nbClasses=4; // nombre de classes souhaitées
		while(true){
			//tirage aléatoire entre 1 et max
			int n=(int)(Math.random()*(max))+1;
			//affichage du résultat entre 1 et 4
			System.out.println("classe :"+((n%nbClasses)+1));
		}
	}
```

---

## Création et appel de méthode statique

- Comment écrire une méthode et l'appeler plusieurs fois ?

```{java methodes}
	/** création d'une méthode affichant le paramètre */
	public static void afficherParametre(double valeur){
		System.out.println("la valeur passée est :" + valeur);
	}

	/** utilisation de la méthode depuis le main*/
	public static void main(String[] args) {
		double val1=3.2;
		//appel avec la variable
		afficherParametre(val1);
		//appel avec une valeur 
		afficherParametre(8.3);
		//appel avec le résultat d'un calcul
		afficherParametre(val1+2);	
	}
```

---

## Recherche de méthodes existantes

- Dans votre code
  - Ecrire le début et \(\mathbf{Ctrl+Espace}\)
  - Afficher la liste des méthodes (\(\mathbf{Ctrl+O}\))
  - Rechercher par nom (\(\mathbf{Ctrl+H}\))
- Dans les librairies
  - Utiliser la javadoc !
  - https://docs.oracle.com/javase/8/docs/api/

---

## Passage de tableaux en paramètres

- Deux tableaux de dimensions différentes ne sont pas du même type !

```{java tableaux_parametre}
  public static void utiliserTableau(int tab[]){
		System.out.println("le premier élément du tableau est :"+tab[0]);
	}
	
	public static void main(String[] args) {
		int tab[]={1,2,3};
		int tab2d[][]={ {1,2},{3,4},{5,6} };
		utiliserTableau(tab);
		//affiche 1
		utiliserTableau(tab2d);
		//The method utiliserTableau(int[]) in the type Essai is not 
		//applicable for the arguments (int[][])
	}
```

---
	
## Solution : surcharge de méthode !

- méthode avec *le même nom* mais des *paramètres différents*

```{java surcharge}
	/** affichage du premier élément d'un tableau 1D */
	public static void utiliserTableau(int tab[]){
		System.out.println("le premier élément du tableau est :"+tab[0]);
	}

	/** affichage du premier élément d'un tableau 2D */
	public static void utiliserTableau(int tab[][]){
		System.out.println("le premier élément du tableau est :"+tab[0][0]);
	}
```

---

## Méthodes de la classe String (1/2)

-	charAt(int index)
  - renvoie les caractère situé à l'indice \(\mathbf{index}\)
- substring(int beginIndex)
  - renvoie la sous-chaine à partir de \(\mathbf{beginIndex}\)
- substring(int beginIndex, int endIndex) (surcharge de la même méthode !)
  - renvoie la sous-chaine entre  \(\mathbf{beginIndex}\) et \(\mathbf{endIndex}\) (non inclus)
```{java charAt}
String str="Bonjour";
str.charAt(2); //renvoie 'n'
str.charAt(5); //renvoie 'u'
str.substring(2); //renvoie "njour"
str.substring(2,5); //renvoie "njo"
str.substring(2,12); //StringIndexOutOfBoundsException !
```

---

## Méthodes de la classe String (2/2)

-	lastIndexOf(int ch)
  - renvoie la dernière occurence du caractère \(\mathbf{ch}\) ou -1 si non trouvé
- lastIndexOf(String str)
   - renvoie la dernière occurence de la chaîne \(\mathbf{str}\) ou -1 si non trouvé

```{java substring}
  String str="Bonjour";
  str.lastIndexOf('r') //renvoie 6
  str.lastIndexOf('z') //renvoie -1
  str.lastIndexOf("jou") //renvoie 3
  str.lastIndexOf("zou") //renvoie -1
```

---

## Méthode *pow* de la classe Math

- Méthode *statique* de la classe Math
- https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#pow-double-double-
- Math.pow(pow(double a, double b))
  - Renvoie a à la puissance b

---

## Casting de double en int et de int vers double

```{java casting}
double a=5.1;
double b=7.2;
//calcul avec des variables de type double 
(a * Math.pow(10, b) + .5) / Math.pow(10, b); // renvoie 5.100000031547867
//casting du résultat en int
(int) ((a * Math.pow(10, b) + .5) / Math.pow(10, b)); // renvoie 5
//casting de l'int en double
(double) ((int) ((a * Math.pow(10, b) + .5) / Math.pow(10, b))); // renvoie 5.0
}
```

--- .title-slide

## Restructuration séance 5 (Classes)

- Classes
- Questions diverses

---

## Structure de base d'une classe

- Nom de la classe == nom du fichier == nom du constructeur !
- Constructeur : méthode appelée automatiquement à la création d'un objet
    - pas de retour : `public void MaClasse` n'est *pas* un constructeur
    
```{}
/* classe définie dans le fichier MaClasse.java */
public class MaClasse{
    private int unNombre; // un attribut
    
    /* constructeur : appelé automatiquement*/
    public MaClasse(){
        unNombre=10; // valeur de l'attribut à la création
    }
}
```

---

## Visibilité

- `public` : peut être manipulé depuis tout le programme
    - concerne généralement les méthodes qui sont connues de l'extérieur
- `private` : ne peut être utilisé que depuis l'objet lui-même
    - les attributs (sauf excellente raison)
    - les méthodes utilisées uniquement dans la classe (détail d'implémentation pouvant être modifié sans danger)
- ... (à suivre)

--- 

## Variables de classe, d'instance et locale
```{java}
public class MaClasse{
    //  variable d'instance (ou attribut)
    private int unNombre; // chaque instance a sa propre valeur
    // variable de classe
    private static int compteur // valeur partagée entre tous les objets de la classe

    public void uneMethode(int param){
        int truc=param*3; // variable locale, n'existe que dans la méthode
        unNombre=truc/2; // l'attribut est manipulable dans toutes les méthodes
    }    
}
```

---

## méthodes : static ou pas static ?

- static : méthode de *classe*
- non static : méthode associée à l'*objet*
```{java}
// définition dans classe Math
public static double random()
// appel dans le programme
Math.random();

// définition dans classe String
public String toLowerCase()
// appel dans le programme
maChaine.toLowerCase();
```

---

## Attributs, accesseurs, mutateurs et this

```{java}
/* classe définie dans le fichier MaClasse.java */
public class MaClasse{
    private int unNombre; //attribut privé, invisible de l'extérieur
    
    /* setteur : mutateur de l'attribut, est public, manipulable de partout */
    public void setUnNombre(int unNombre){
        this.unNombre=unNombre; //this fait référence à l'attribut
    }
    
    /* getter : accesseur de l'attribut, est public, donne accès en lecture */
    public int getUnNombre(){
        return unNombre;
    }
}

```

---

## Divers

- vocabulaire / lexique
- passage par valeur ou référence 
   -  http://stackoverflow.com/questions/40480/is-java-pass-by-reference-or-pass-by-value
- connaître la valeur des variables pendant l'exécution
   - http://www.vogella.com/tutorials/EclipseDebugging/article.html

--- .title-slide

## Restructuration séance 6

- Constructeurs
- Héritage

---

## Constructeur par défaut

- Le constructeur par défaut est créé automatiquement par JAVA si aucun n'est défini
- Il permet la création d'un objet avec les valeurs d'attributs par défaut
```{java}
public class A{
    private int unEntier;
    private double un Reel;
}

//main : création de l'objet avec *invocation* (appel) du constructeur par défaut
A unObjetA=new A(); //unEntier vaut 0 - unReel vaut 0.0
```

---

## Constructeur défini

- Si au moins un constructeur est défini, seuls les constructeurs explicitement définis peuvent être utilisés 
```{java}
public class A{
    private int unEntier;
    private double un Reel;
    
    public A(int entier){
        this.unEntier=entier; // affectation de la valeur de l'argument à l'attribut
        this.unReel=3.14 // valeur d'initilisation fixée par le constructeur
    }
}

//main
A unObjetA=new A(); // ne compile pas
A unObjetA=new A(8); // unEntier vaut 8 - unReel vaut 3.14
```

---

## Constructeur et héritage

- Une classe fille *ajoute* des attributs par rapport à la classe mère
- L'utilisation de super() dans le constructeur permet de ne pas répéter le code des attributs communs
```{java}
public class B extends A{
    //unEntier et unReel sont déjà définis dans A
    private String uneChaine;

    public B(int entier, String chaine){
        super(entier); // appelle le constructeur de A
        this.uneChaine=chaine;
    }
}

// création de l'objet - unEntier vaut 10 - unReel vaut 3.14 - uneChaine vaut "test"
B unObjetB=new B(10,"test");
```

---

## Visibilité

- `public` : peut être manipulé depuis tout le programme
    - concerne généralement les méthodes qui sont connues de l'extérieur
- `private` : ne peut être utilisé que depuis l'objet lui-même
    - les attributs (sauf excellente raison)
    - les méthodes utilisées uniquement dans la classe (détail d'implémentation pouvant être modifié sans danger)
- `protected` : est visible uniquement des classes filles
    - peut être redéfinie par la classe fille

--- 


## Doit-on hériter toutes les méthodes ?

- Une classe fille récupère (hérite) automatiquement toutes les méthodes de la classe mère
- Il est possible de **redéfinir** une (ou plusieurs) méthodes pour *changer* ou *compléter* le comportement
- L'appel de la méthode de la classe mère se fait avec le mot clé **super**

```{java}
public class A{
    public double uneMethode(double var){
        return var / 2;
    }
}

public class B extends A{ //A est la super classe de B
    //redéfinition réutilisant et complétant la méthode de la super classe
    public double uneMethode(double var){
        return super.uneMethode(var) + 1;
    }
}
```

---

## Que se passe-t-il si B hérite de A et C hérite de B ?

```{java}
public class A{
    public void afficher(){System.out.println("Bonjour depuis A !!");}
}
public class B extends A{
    // rien de spécial
}
public class C extends B{
    // rédéfinition !
    public void afficher(){System.out.println("Bonjour depuis C !!");}
}

//main 
A objA=new A(); objA.afficher(); // affiche Bonjour depuis A !!
B objB=new B(); objB.afficher(); // affiche Bonjour depuis A !!
C objC=new C(); objC.afficher(); // affiche Bonjour depuis C !!
```

---

## Covariance

- un tableau de type A peut contenir des objets de type B si (et seulement si) B hérite de A

(A est la superclasse de B)

```{java}

A tabDeA[] ; //déclaration d'un tableau de A
tabDeA = new A[50]; // allocation mémoire

A unA=new A(); // création d'un objet de type A
B unB=new B(); // création d'un objet de type B

tabDeA[0]=unA; 
tabDeA[1]=unB; //OK, si B hérite de A
```

- version longue : https://dzone.com/articles/covariance-and-contravariance

---

## Que contient le tableau de la page 107 ?

```{java}
Ville[] tableau = new Ville[6];
tableau[0] = new Ville("Marseille", 13000, "France");
tableau[1]= new Capitale("Paris", 75000, "France", "la tour Eiffel");

```

- tableau accepte des objets de type **Ville** *et ses sous-classes* (dont **Capitale**)
- chaque case de tableau contient la **valeur de l'adresse mémoire** de l'objet
- à la compilation, seules les méthodes définies dans **Ville** sont utilisables
- à l'exécution, la méthode de **l'objet** est utilisée (y compris si elle est redéfinie)

```{java}
tableau[1].decrisToi(); // appel de la méthode de l'objet référencé
Object truc = tableau[1];
truc.decrisToi(); // ne compile pas ! decrisToi() n'est pas défini pour Object
truc.toString(); //OK, car toString() est défini pour tous les objets !
```

---

## Retour sur le transtypage

- Transtypage : conversion du type d'un objet en un autre type

```{java}
//exemple avec type primitif
int a=5;
double resultat = a/2; // division entre 2 entiers, resultat vaut 2
resultat = (double) a /2; // transtypage de a : resultat vaut 2.5

//exemple de transtypage entre classes
Object truc = new Ville("Marseille", 13000, "France");
truc.decrisToi(); // ne compile pas ! decrisToi() n'est pas défini pour Object
(Ville) truc.decrisToi(); // truc est transtypé, la méthode decrisToi() est utilisable
```

- permet la compilation, mais crash à l'exécution si l'objet n'est pas du bon type

```{java}
// compile mais crashe à l'exécution si NestPasUneVille ne définit pas decrisToi() 
Objet machin= new NestPasUneVille("nimportequoi");
(Ville) machin.decrisToi(); //crash si NestPasUneVille ne définit pas decrisToi()
```

---

## hashCode() et equals()

- méthodes de la classe **Object** définie (ou redéfinie) pour tous les objets
- permettent les opérations de *classication* et de *comparaison*

```{java}
//hashCode définit un identifiant unique pour chaque objet de la Classe Ville
public int hashCode(){
    return (this.nomPays.hashCode()+this.nomVille.hashCode());
}

//equals définit les critères d'égalité d'un objet avec un autre
public boolean equals(Ville v){
    return (this.hashCode() == v.hashCode() &&
        this.getNombreHabitant() == v.getNombreHabitant());
}
```

---

## Questions diverses

- Pourquoi `boolean flag = Boolean.getBoolean("true");` renvoie toujours false ?
- Peut-on utiliser A.i n'importe où si i est défini comme :
```{java}
class A{
public static final int i;
} 
```
- Retour sur les boucles

--- .title-slide

## Restructuration séance 7

- Les collections
- La généricité
- Retour sur l'héritage

---

## Que faut-il retenir ?

- Deux interfaces utiles : *List* et *Map*

- Une liste est un *tableau dynamique* 
    - pas de taille limite
    - méthodes pour les différents opérations
    - A connaitre : **ArrayList**

- Un map est un système *clé/valeur*
    - La clé identifie l'objet (remplace l'index)
    - La valeur est l'objet lui-même
    - A connaitre : **HashMap**

---

## Opérations 

- Sur les listes https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html
    - ajout : *add*
    - récupération : *get*
    - existence : *contains*
    - suppression : *remove* 
- Sur les map https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html
    - ajout : *put*
    - récupération : *get* (retourne *null* si clé non trouvée)
    - existence : *containsKey*/*containsValue*
    - suppression : *remove*

---

## Généricité ?
- Sans généricité ?
    - Les valeurs insérées sont considérées de type *Object*
    - La valeur doit être castée à la récupération
```{java}
    Arraylist al= new ArrayList();
    al.add("Une chaine");
    String chaine=(String)al.get(0);
```

- Fixe les valeurs autorisées
    - Garantit l'insertion d'objets de la classe fixée entre < et >
    - Garantit de récupérer des objet de cette classe
```{java}
    ArrayList<String> al=new ArrayList<String>();
    al.add("Une chaine");
    String chaine=al.get(0);
```

---

## Itérations simples sur Hashmap

- Sur *ArrayList*
```{java}
ArrayList<Double> al=new ArrayList<Double>();
for (Double valeur : al) {
	System.out.println(valeur);
}
```

- Sur *Hashmap*

```{java}
Map<String, Integer> map = new HashMap<String, Integer>();
for (Map.Entry<String, Integer> entry : map.entrySet()) {
    System.out.println("clé = " + entry.getKey() + ", valeur = " + entry.getValue());
}
```

---

## Utilisation explicite de la classe Iterator

- ArrayList
```{java}
ArrayList<Double> al=new ArrayList<Double>();
Iterator<String> listIterator = al.iterator();
while (listIterator.hasNext()) {
	System.out.println(listIterator.next());
}
```
- Map
```{java}
Map<String, Integer> map = new HashMap<String, Integer>();
Iterator<Map.Entry<String, Integer>> entrees = map.entrySet().iterator();
while (entrees.hasNext()) {
    Map.Entry<String, Integer> entry = entrees.next();
    System.out.println("Key = " + entrees.getKey() + ", Value = " + entrees.getValue());
}
```

---

## Héritage et constructeur avec paramètre

- Classe `Personne` : 3 attributs `nom`, `prenom`, `age`
- Constructeur avec paramètre `public Personne(String nom, String prenom, int age)`
- Les sous-classes doivent définir un constructeur qui appelle ce constructeur avec `super`

```{java}
Classe Inconnu extends Personne
    String lieu;
    public Inconnu(int age, String lieu)
        super("John","Doe",age)
        this.lieu=lieu;
```

--- .title-slide

## Restructuration séance 8

- Les exceptions
- Les fichiers texte

---

## Les exceptions : est-ce vraiment utile ?

Oui

## Est-ce dangereux, prématuré ?

Non, indispensable

---

## Pourquoi ?

- Evite de mélanger le code "utile" et la gestion des erreurs 
    - débat ouvert : https://golang.org/doc/faq#exceptions
- La valeur de retour d'une méthode n'est pas toujours disponible pour indiquer une erreur
    - exemple extrême : le constructeur n'a pas de valeur de retour !
- Les classes que vous importez peuvent implémenter des exceptions qu'il faut savoir gérer
    - par exemple, pour gérer les fichiers...

---

## Exemple du constructeur

```{java}
public class AgeValide {
	int age;
    
    //Le constructeur n'accepte de créer l'objet que si l'argument est valide
	public AgeValide(int age) {
		if (age >=0 && age < 125)
			this.age = age;
		else{
			throw new IllegalArgumentException();
		}
	}

```

---

## Doit-on utiliser obligatoirement try..catch ?

```{java}
	public static void main(String[] args) {
		AgeValide valide=new AgeValide(20);  // objet créé
		AgeValide nonvalide=new AgeValide(300); // exception
		System.out.println("fin du programme");
    }
```
Le programme crashe et affiche :

<code>  Exception in thread "main" java.lang.IllegalArgumentException<br>
	    at AgeValide.<init>(AgeValide.java:9)<br>
	    at AgeValide.main(AgeValide.java:15)
</code>

---

## Avec try..catch 

```{java}
	public static void main(String[] args) {
		try{
			AgeValide valide=new AgeValide(20);
			AgeValide nonvalide=new AgeValide(300);
		}catch(Exception e){
			e.printStackTrace(); //affiche l'exception
		}
		System.out.println("sortie du programme");
}
```
<code>java.lang.IllegalArgumentException<br>
	at AgeValide.<init>(AgeValide.java:9)<br>
	at AgeValide.main(AgeValide.java:16)<br>
sortie du programme</code>

---

## Multiples catchs

- Les exceptions sont des *objets* issus d'une hiérarchie dont la racine est *Exception*
    - Exemple : https://docs.oracle.com/javase/8/docs/api/java/lang/IllegalArgumentException.html
- Lorsqu'une exception est levée, les catch sont analysés dans l'ordre de leur déclaration
- Un catch est traité si l'objet *appartient* à ou est un *descendant* de la classe Exception en paramètre du catch
    - Une exception issue de la classe `ArithmeticException` sera donc traitée par `catch(ArithmeticException e)` tout comme par `catch(Exception  e)`

---

## InputStream/OutputStream

---

## Lecture/Ecriture d'un fichier dans/en dehors du projet


---

## Questions diverses

- Sérialisation
    - Objectif d'apprentissage à connaitre, pas à appliquer
    - Permet de sauvegarder l'état d'un objet et de le "transporter"
    - Transient : indique les éléments à ne *pas* sérialiser
    
- Travail sur fichiers "tableurs"
    - Excel : https://poi.apache.org/
    - CSV :http://www.mkyong.com/java/how-to-read-and-parse-csv-file-in-java/
    - Langage (non JAVA) adapté à l'exploration de données : https://www.r-project.org/
    
- Pourquoi on ajoute les `java.io.File`, `java.io.FileInputStream`, `java.io.FileOutputSteam`, `java.io.IOException`, ...
    - Ces classes sont définies en dehors de `java.lang`, ils faut donc les importer
